# ci は lint と test を行います。
# タイミングは main, dev 両ブランチへの push, pr です。

name: ci

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

  workflow_dispatch:

jobs:

  lint-and-test-with-cache:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        # NOTE: cache option を使いません。
        #       actions/cache@v2 で node_modules をキャッシュしたほうが yarn install が高速で終わるためです。

    - uses: actions/cache@v2
      id: node_modules_cache_id
      with:
        path: |
          node_modules
        key: node-v${{ matrix.node-version }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

    - run: yarn install

    - run: yarn lint

    - run: yarn test:unit
